name: CI Next.js

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # Travail de vérification du code
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Détection du gestionnaire de paquets
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "lint=yarn lint" >> $GITHUB_OUTPUT
            echo "test=yarn test" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "lint=npm run lint" >> $GITHUB_OUTPUT
            echo "test=npm run test" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Impossible de déterminer le gestionnaire de paquets"
            exit 1
          fi

      - name: Configuration de Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Restauration du cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Installation des dépendances
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Exécution de lint
        run: ${{ steps.detect-package-manager.outputs.lint }}
        continue-on-error: false

      - name: Exécution des tests (si disponible)
        run: ${{ steps.detect-package-manager.outputs.test }}
        continue-on-error: true

      - name: Notification de résultat
        if: always()
        run: echo "Vérification du code terminée !"